# build stage
FROM golang:1.17-alpine AS builder
WORKDIR /go/src/app
ADD https://raw.githubusercontent.com/mikakatua/devops-challenge/master/app/server.go .
RUN go mod init && go build -o /app

# final stage
FROM alpine:3.15
WORKDIR /
COPY --from=builder /app .
COPY static ./static
EXPOSE 8080
USER nobody
CMD ["/app"]
