apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.application_name }}
  name: {{ template "service.name" . }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Values.application_name }}
  type: {{ .Values.service.type }}
