apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.name" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.certificate | b64enc }}
  tls.key: {{ .Values.ingress.key | b64enc }}
