name: CI/CD

on:
  # Triggers the workflow on push events
  push:
    branches:
      - develop
      - master
    paths: 
      - '2_application/**'
      - '!2_application/**.md'
      - '!2_application/static/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      cluster_name:
        description: Provided by Terraform output
        required: true
      github_identity_provider:
        description: Provided by Terraform output
        required: true
      github_service_account:
        description: Provided by Terraform output
        required: true
      k8s_application:
        description: Provided by Terraform output
        required: true
      k8s_namespace:
        description: Provided by Terraform output
        required: true
      k8s_service_account:
        description: Provided by Terraform output
        required: true
      project_id:
        description: Provided by Terraform output
        required: true
      region:
        description: Provided by Terraform output
        required: true
      repository_name:
        description: Provided by Terraform output
        required: true
          
jobs:
  build:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest

    # Set permissions for GitHub API
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Authengicate GitHub Actions Workflows to Google Cloud via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ github.event.inputs.github_identity_provider }}
          service_account: ${{ github.event.inputs.github_service_account }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker ${{ github.event.inputs.region }}-docker.pkg.dev

      # Generate tag with the commit hash
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.event.inputs.repository_name }}/${{ github.event.inputs.k8s_application }}
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=latest

      # Configure docker daemon to use BuildKit
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      # Cache docker build to speed up workflow 
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          context: ${{ github.workspace }}/2_application
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - run: 'helm version'

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    # Set permissions for GitHub API
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Authengicate GitHub Actions Workflows to Google Cloud via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ github.event.inputs.github_identity_provider }}
          service_account: ${{ github.event.inputs.github_service_account }}

      - name: Get Kubernetes credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ github.event.inputs.cluster_name }}
          location: ${{ github.event.inputs.region }}
          project_id: ${{ github.event.inputs.project_id }}

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - id: 'get-pods'
        run: 'kubectl get pods'
      

     
