name: CI/CD

on:
  # Triggers the workflow on push events to master
  push:
    branches:
      - master
    paths: 
      - '2_application/**'
      - '!2_application/**.md'
      - '!2_application/static/**'


  # Allows trigger the workflow manually
  workflow_dispatch:

jobs:
  cicd:
    name: Build & Deploy
    runs-on: ubuntu-latest

    # Set permissions for GitHub API
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=${{ github.workspace }}/1_infrastructure init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_KEY }}
      
      # Set environment variables from Terraform outputs
      - name: Set environment
        run: |
          echo 'cluster_name<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw cluster_name | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'github_identity_provider<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw github_identity_provider | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'github_service_account<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw github_service_account | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'k8s_application<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw k8s_application | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'k8s_namespace<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw k8s_namespace | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'k8s_service_account<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw k8s_service_account | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'project_id<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw project_id | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'region<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw region | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'repository_name<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw repository_name | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'static-web-bucket<<EOF' >> $GITHUB_ENV
          terraform -chdir=${{ github.workspace }}/1_infrastructure output -raw static-web-bucket | grep Terraform | cut -f1 -d: >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_KEY }}

      # Authengicate GitHub Actions Workflows to Google Cloud via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.github_identity_provider }}
          service_account: ${{ env.github_service_account }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - name: Add Docker credential helper    
        run: |-
          gcloud --quiet auth configure-docker ${{ env.region }}-docker.pkg.dev

      # Generate tag with the commit hash
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.repository_name }}/${{ github.event.inputs.k8s_application }}
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=latest

      # Configure docker daemon to use BuildKit
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      # Cache docker build to speed up workflow 
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          context: ${{ github.workspace }}/2_application
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Configure authentication to GKE via a kubeconfig file
      - name: Get Kubernetes credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.cluster_name }}
          location: ${{ env.region }}
          project_id: ${{ env.project_id }}

      # Apply manifests generated by Helm templates
      - name: Kubernetes deployment
        run: |-
          helm template ${{ github.workspace }}/2_application/k8s \
            --set application_name=${{ env.k8s_application }} \
            --set bucket_name=${{ env.static-web-bucket }} \
            --set image.repository=${{ env.repository_name }}/${{ github.event.inputs.k8s_application }} \
            --set image.tag=latest \
            --set service_account=${{ env.k8s_service_account }} \
            --set ingress.certificate="${{ secrets.TLS_CRT }}" \
            --set ingress.key="${{ secrets.TLS_KEY }}" \
          | kubectl -n ${{ env.k8s_namespace }} apply -f -

